

GET http://localhost:4000/nilai

###
POST http://localhost:4000/alternatif
Content-Type: application/json
{
    "nama_alternatif": "John Doe",
    "no_kk": "1234567890",
    "jenis_kelamin": "Laki-laki",
    "alamat": "Jl. Contoh No. 123",
    "no_telp": "081234567890",
    "pekerjaan": "Pegawai Swasta"
}


###
GET http://localhost:4000/kriteria 
Content-Type: application/json

{
    "nama_kriteria":"lantai",
    "bobot":3,
    "jenis":"benefit",
    "keterangan":"tanah"
}

###
GET http://localhost:4000/topsis
###
GET http://localhost:4000/topsistest


