###
POST http://localhost:4000/kriteria
Content-Type: application/json

{
    "nama_kriteria": "Pekerjaan",
    "alternatif_Id":1,
    "sifat": "pegawai",
    "bobot": 4
}

###
GET http://localhost:4000/alternatifKriteria/2


